module:
  action: 0
  aggregator: 0
  automated_cron: 0
  bamboo_twig: 0
  bamboo_twig_config: 0
  bamboo_twig_extensions: 0
  bamboo_twig_file: 0
  bamboo_twig_i18n: 0
  bamboo_twig_loader: 0
  bamboo_twig_path: 0
  bamboo_twig_security: 0
  bamboo_twig_token: 0
  basic_auth: 0
  block: 0
  block_content: 0
  breakpoint: 0
  ckeditor: 0
  clever_theme_switcher: 0
  codemirror_editor: 0
  color: 0
  comment: 0
  config: 0
  config_inspector: 0
  config_update: 0
  config_update_ui: 0
  conflict: 0
  contact: 0
  content_moderation: 0
  context: 0
  context_ui: 0
  contextual: 0
  ctools: 0
  datetime: 0
  datetime_range: 0
  dblog: 0
  devel: 0
  display_field_copy: 0
  ds_devel: 0
  ds_switch_view_mode: 0
  dynamic_page_cache: 0
  editor: 0
  entity_reference: 0
  facets: 0
  facets_range_widget: 0
  facets_rest: 0
  facets_summary: 0
  field: 0
  field_layout: 0
  field_permissions: 0
  field_ui: 0
  file: 0
  file_mdm: 0
  file_mdm_exif: 0
  filter: 0
  form_mode_manager: 0
  form_mode_manager_theme_switcher: 0
  format_strawberryfield: 0
  hal: 0
  help: 0
  history: 0
  image: 0
  imagemagick: 0
  inline_entity_form: 0
  inline_form_errors: 0
  jsonapi: 0
  jsonld: 0
  key_value: 0
  kint: 0
  language: 0
  layout_discovery: 0
  link: 0
  media: 0
  media_library: 0
  menu_export: 0
  menu_ui: 0
  migrate: 0
  migrate_drupal: 0
  mobile_device_detection: 0
  module_missing_message_fixer: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  quick_node_clone: 0
  quickedit: 0
  rdf: 0
  rdf_builder: 0
  rdfui: 0
  responsive_image: 0
  rest: 0
  restui: 0
  s3fs: 0
  search_api: 0
  search_api_autocomplete: 0
  search_api_solr: 0
  search_api_solr_defaults: 0
  serialization: 0
  settings_tray: 0
  shortcut: 0
  simpletest: 0
  strawberryfield: 0
  system: 0
  taxonomy: 0
  telephone: 0
  text: 0
  token: 0
  tokenuuid: 0
  toolbar: 0
  tour: 0
  tracker: 0
  twig_field: 0
  twig_tweak: 0
  update: 0
  user: 0
  views_ui: 0
  webform: 0
  webform_examples_accessibility: 0
  webform_image_select: 0
  webform_node: 0
  webform_scheduled_email: 0
  webform_strawberryfield: 0
  webform_submission_log: 0
  webform_templates: 0
  webform_ui: 0
  webform_views: 0
  webprofiler: 0
  workflows: 0
  ds: 1
  menu_link_content: 1
  pathauto: 1
  webform_bootstrap: 1
  ds_extras: 2
  content_translation: 10
  views: 10
  standard: 1000
theme:
  stable: 0
  classy: 0
  bartik: 0
  seven: 0
  bootstrap_barrio: 0
  archipelago_subtheme: 0
  esie_subtheme: 0
profile: standard
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
