definitions:
  contact__site_page:
    enabled: true
    menu_name: footer
    parent: ''
    weight: 0
    expanded: false
  standard__front_page:
    enabled: false
    menu_name: main
    parent: ''
    expanded: false
    weight: 0
  user__page:
    weight: -49
    menu_name: account
    parent: ''
    enabled: true
    expanded: false
  user__logout:
    weight: -48
    menu_name: account
    parent: ''
    expanded: false
    enabled: true
  node__add_page:
    weight: -46
    menu_name: tools
    parent: ''
    expanded: false
    enabled: false
  tracker__page:
    weight: -47
    menu_name: tools
    parent: ''
    enabled: false
    expanded: false
  aggregator__feed_add:
    weight: -50
    menu_name: tools
    parent: ''
    enabled: false
    expanded: false
  aggregator__page_last:
    weight: -42
    menu_name: tools
    parent: ''
    expanded: false
    enabled: false
  filter__tips_all:
    weight: -49
    menu_name: tools
    parent: ''
    expanded: false
    enabled: false
_core:
  default_config_hash: jdY7AU0tU-QsjmiOw3W8vwpYMb-By--_MSFgbqKUTYM
