id: raw_metadata
label: 'Raw Collection Metadata'
ui_limit: 'digital_object_collection|*'
properties:
  field_id: node.digital_object_collection.field_descriptive_metadata
type: display_field_copy
type_label: 'Copy field'
entities:
  node: node
