id: formatted_metadata
label: 'Formatted Object Metadata'
ui_limit: 'digital_object|*'
properties:
  field_id: node.digital_object.field_descriptive_metadata
type: display_field_copy
type_label: 'Copy field'
entities:
  node: node
